#!/bin/sh

# MADE BY MAEL A.
# Repositorie: https://github.com/maelsan/faker-push

###
 # NOTE: Put your informations here (path + folder name)
 #     : If the folder is already created (or repo already cloned), nothing will be changed.
###
DIRGIT="$HOME/Repos/"; # Path of your fake repo
DIRNAME="faker-push/"; # Name of your repo
BRANCH="master" # Branch name
MESSAGE="https://github.com/maelsan/faker-push"

HOWMANY=$((RANDOM%50+1)) # Quantity of fake commit, you can change this value

FakerGo () {
	if [ -d "$DIRGIT$DIRNAME" ]; then
		if [ -d "$DIRGIT$DIRNAME".git ]; then
			cd "$DIRGIT$DIRNAME"

			git fetch --all --quiet
			git reset --hard origin/master --quiet
			uuidgen > "$DIRGIT$DIRNAME".faker
			git add -f .faker >/dev/null
			git commit -m "$MESSAGE" >/dev/null
			git push origin "$BRANCH" --quiet;

			HOWMANY=$((HOWMANY-1))

			while [ "$HOWMANY" -gt 0 ]; do
				FakerGo
			done
		fi
	else
		noFolder
	fi
}

###
 # Folder not available? We create him.
###
noFolder () {
	cd "$DIRGIT" || exit
	mkdir faker 
	FakerGo
}

FakerGo # - Run script